
include(GNUInstallDirs)

if(WITH_PORTABLE OR WIN32)
    # flatten everything
    set(CMAKE_INSTALL_BINDIR "${CMAKE_INSTALL_PREFIX}")
    set(CMAKE_INSTALL_LIBDIR "${CMAKE_INSTALL_PREFIX}/lib")
    set(CMAKE_INSTALL_DATADIR "${CMAKE_INSTALL_PREFIX}")
    set(LETOS_INSTALL_DATADIR "${CMAKE_INSTALL_DATADIR}")
    set(LETOS_INSTALL_PLUGINDIR "${CMAKE_INSTALL_BINDIR}/plugins")
    set(LETOS_INSTALL_STYLEDIR "${CMAKE_INSTALL_BINDIR}/styles")
else()
    set(LETOS_INSTALL_DATADIR "${CMAKE_INSTALL_DATADIR}/letos")
    set(LETOS_INSTALL_PLUGINDIR "${CMAKE_INSTALL_LIBDIR}/letos")
    set(LETOS_INSTALL_STYLEDIR "${LETOS_INSTALL_PLUGINDIR}/styles")
endif()
